version: '3'

services:
  mpdnode0:
    container_name: mpdnode0
    image: "tendermint/mpdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-mpd.log}
    volumes:
      - ./build:/mpd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  mpdnode1:
    container_name: mpdnode1
    image: "tendermint/mpdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-mpd.log}
    volumes:
      - ./build:/mpd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  mpdnode2:
    container_name: mpdnode2
    image: "tendermint/mpdnode"
    environment:
      - ID=2
      - LOG=${LOG:-mpd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/mpd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  mpdnode3:
    container_name: mpdnode3
    image: "tendermint/mpdnode"
    environment:
      - ID=3
      - LOG=${LOG:-mpd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/mpd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.10.0/16