version: '3'

services:
  marketplace_ibc0:
    container_name: marketplace_ibc0
    image: "dwh_marketplace:latest"
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 26657:26657
    environment:
      - CHAIN_ID=ibc0
      - RESET=true
      - VIRTUAL_PORT=26657
      - VIRTUAL_HOST=demo-ibc0-node.openmarket.one
      - LETSENCRYPT_HOST=demo-ibc0-node.openmarket.one

  marketplace_api_ibc0:
    container_name: marketplace_api_ibc0
    image: "dwh_marketplace:latest"
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "mpcli rest-server --chain-id mpchain --trust-node --laddr tcp://0.0.0.0:1317 --node=tcp://marketplace_ibc0:26657"
    ports:
      - 1317:1317
    environment:
      - VIRTUAL_PORT=1317
      - VIRTUAL_HOST=demo-ibc0-rest.openmarket.one
      - LETSENCRYPT_HOST=demo-ibc0-rest.openmarket.one
