version: '3'

services:
  marketplace_ibc1:
    container_name: marketplace_ibc1
    image: "dwh_marketplace:latest"
    restart: unless-stopped
    volumes:
      - ./data:/data
      - mp-ibc1-data:/root
    ports:
      - 26557:26657
    networks:
      - dwh-tier
    environment:
      - RESET=true
      - VIRTUAL_PORT=26657
      - VIRTUAL_HOST=demo-ibc1-node.openmarket.one
      - LETSENCRYPT_HOST=demo-ibc1-node.openmarket.one

  marketplace_api_ibc1:
    container_name: marketplace_api_ibc1
    image: "dwh_marketplace:latest"
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "mpcli rest-server --chain-id mpchain --trust-node --laddr tcp://0.0.0.0:1317 --node=tcp://marketplace_ibc1:26657"
    ports:
      - 1318:1317
    networks:
      - dwh-tier
    environment:
      - VIRTUAL_PORT=1317
      - VIRTUAL_HOST=demo-ibc1-rest.openmarket.one
      - LETSENCRYPT_HOST=demo-ibc1-rest.openmarket.one

volumes:
  mp-ibc1-data:

networks:
  dwh-tier:
    external:
      name: dwh-network